Adding tests for Selling stock
CSC207-2022F-UofT/course-project-Team-Stonks pull request #42
Opened 2022-11-25 20:22 UTC by Peaceful36

Made some tests for sell-stock use case.

2022-11-25 20:53 UTC, inaam10-tech requested changes
I believe you have one failed test, you might want to check on that before merging

2022-11-25 21:35 UTC, Peaceful36 commented
> I believe you have one failed test, you might want to check on that before merging

I have fixed the errors in my tests.

2022-11-25 23:59 UTC, jackzxliu approved these changes
Looks good

2022-11-26 00:21 UTC, inaam10-tech submitted a review, later dismissed
Seems good now.

2022-11-26 01:06 UTC, noel-toms approved these changes
Everything seems good

2022-11-26 01:40 UTC, eladperlman requested changes
You should add more tests, also the numbers you use in your scenarios such as buying "4" stocks should be stored as a constant, I see those magic numbers all over the file.

2022-11-26 02:02 UTC, noel-toms commented on src/test/java/SellStockTest/SellStockTest.java
> +public class SellStockTest {
To add to this I think it's very important to make tests concerning the database, as selling stocks removes the stock based on the quantity from the user. Something worth considering might be to make test tables in the database and fill them with values, and the assure that after selling a stock that the quantity of that stock has decreased.

2022-11-26 02:03 UTC, noel-toms commented
> You should add more tests, also the numbers you use in your scenarios such as buying "4" stocks should be stored as a constant, I see those magic numbers all over the file.

To add to this I think it's very important to make tests concerning the database, as selling stocks removes the stock based on the quantity from the user. Something worth considering might be to make test tables in the database and fill them with values, and the assure that after selling a stock that the quantity of that stock has decreased.

2022-11-27 20:06 UTC, inaam10-tech submitted a review, later dismissed
All good now

2022-11-27 22:42 UTC, Peaceful36 commented on src/test/java/SellStockTest/SellStockTest.java
> +public class SellStockTest {
I have added test and made use of constants

2022-11-27 23:02 UTC, Spaghetti-12 reviewed
Looks good!

2022-11-27 23:02 UTC, Spaghetti-12 approved these changes

2022-11-28 05:23 UTC, eladperlman approved these changes
Looks good!

2022-11-28 17:03 UTC, noel-toms approved these changes
Approved.

2022-11-28 17:04 UTC, merged